apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql-deploy
  namespace: smack
  labels:
    app: mysql
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      type: db
  template:
    metadata:
      name: mysql-pod
      namespace: smack 
      labels:
        app: mysql
        type: db
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: rootPassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: userpass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport-svc
  namespace: smack
  labels:
    type: nodeport
    env: dev
spec:
  type: NodePort
  selector:
    app: mysql
    type: db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32306